version: '2.0'
services:
  web:
    container_name: docker-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html/src
      - ../vendor:/var/www/html/vendor
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    env_file:
    - ./env.conf

  php:
    container_name: docker-php
    # image: php:fpm
    build: ./php-fpm
    volumes:
      - ../src:/var/www/html/src
      - ../vendor:/var/www/html/vendor
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 var_display_max_data=1024 var_display_max_depth=5"
    env_file:
    - ./env.conf